# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-06 04:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('name', models.CharField(default='ram', max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('profileImage', models.FileField(default='jon.jpg', upload_to=b'')),
                ('age', models.IntegerField(default=0)),
                ('gender', models.CharField(default='M', max_length=1)),
                ('college', models.CharField(default='NITW', max_length=100)),
                ('branch', models.CharField(default='CSE', max_length=100)),
            ],
        ),
    ]
