# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-06 14:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_groupdiscussion_project_userchat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='groupDiscussion',
        ),
    ]
