# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-06 12:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_remove_project_groupdiscussion'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='members',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='project',
            name='request',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profileImage',
            field=models.FileField(default='jon.jpg', upload_to=''),
        ),
    ]
