# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-06 15:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20180106_1816'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='request',
            new_name='requests',
        ),
    ]
